# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPagSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField()),
                ('sender_area_code', models.IntegerField()),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_email', models.TextField()),
                ('sender_cpf', models.CharField(max_length=11)),
                ('shipping_street', models.TextField()),
                ('shipping_number', models.IntegerField(blank=True, null=True)),
                ('shipping_complement', models.TextField(blank=True, null=True)),
                ('shipping_district', models.TextField()),
                ('shipping_postalcode', models.CharField(max_length=8)),
                ('shipping_city', models.TextField()),
                ('shipping_state', models.CharField(max_length=2)),
                ('shipping_country', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('1', 'boleto'), ('2', 'cart\xe3o')], max_length=1)),
                ('pagseguro_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itempayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.PaymentPagSeguro'),
        ),
    ]
