# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpagseguro',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Iniciado'), ('WAITING_PAYMENT', 'Aguardando pagamento'), ('IN_REVIEW', 'Em revis\xe3o'), ('APPROVED', 'Aprovado'), ('AVAILABLE', 'Dispon\xedvel'), ('IN_DISPUTE', 'Em disputa'), ('RETURNED', 'Retornado'), ('CANCELLED', 'Cancelado'), ('SELLER_CHARGEBACK', 'Estorno'), ('CONTESTATION', 'Contesta\xe7\xe3o'), ('PROCESSING_REFUND', 'Processando estorno'), ('PRE_AUTHORIZED', 'Pr\xe9 autorizado')], default='APPROVED', max_length=18),
            preserve_default=False,
        ),
    ]
