# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_paymentpagseguro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpagseguro',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Iniciado'), ('1', 'Aguardando pagamento'), ('2', 'Em revis\xe3o'), ('3', 'Aprovado'), ('4', 'Dispon\xedvel'), ('5', 'Em disputa'), ('6', 'Retornado'), ('7', 'Cancelado'), ('8', 'Estorno'), ('9', 'Contesta\xe7\xe3o'), ('10', 'Processando estorno'), ('11', 'Pr\xe9 autorizado')], max_length=2, null=True),
        ),
    ]
