# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20170112_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpagseguro',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentpagseguro',
            name='sender_birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
